version: '2'
services:
  flipdot-clock:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flipdot-clock
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./config.ini:/app/config.ini      
    environment:
      - "TZ=America/Chicago"

